# Generated by Django 6.0.6 on 2026-08-29 10:39

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at_server', models.DateTimeField(auto_now_add=True)),
                ('updated_at_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at_server', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('designation', models.CharField(blank=True, default='Sales Consultant', max_length=100, null=True)),
                ('personal_rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'Workspace Owner'), ('admin', 'Agency Admin'), ('agent', 'Sales Consultant'), ('partner', 'Channel Partner')], default='agent', max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['full_name', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at_server', models.DateTimeField(auto_now_add=True)),
                ('updated_at_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at_server', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('official_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_color_hex', models.CharField(default='#1E3A8A', max_length=10)),
                ('secondary_color_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('pdf_template_id', models.CharField(default='modern_minimal', max_length=50)),
                ('show_company_logo_on_pdf', models.BooleanField(default=True)),
                ('show_company_phone_on_pdf', models.BooleanField(default=True)),
                ('show_company_email_on_pdf', models.BooleanField(default=True)),
                ('show_company_address_on_pdf', models.BooleanField(default=True)),
                ('show_company_website_on_pdf', models.BooleanField(default=True)),
                ('show_agent_name_on_pdf', models.BooleanField(default=True)),
                ('show_agent_phone_on_pdf', models.BooleanField(default=True)),
                ('show_agent_rera_on_pdf', models.BooleanField(default=True)),
                ('show_company_rera_on_pdf', models.BooleanField(default=True)),
                ('show_qr_code_on_pdf', models.BooleanField(default=True)),
                ('footer_disclaimer_text', models.TextField(blank=True, null=True)),
                ('invite_code', models.CharField(db_index=True, default=accounts.models.generate_invite_code, max_length=12, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at_server'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['invite_code'], name='tenants_invite__2bba4e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['updated_at_server'], name='tenants_updated_8ff43d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'role'], name='users_tenant__b30c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'updated_at_server'], name='users_tenant__dc61f2_idx'),
        ),
    ]
