# Generated by Django 6.1.1 on 2026-09-20 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0002_userdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area_value',
            new_name='carpet_area',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='amenities_notes',
            new_name='internal_private_notes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bhk',
        ),
        migrations.AddField(
            model_name='property',
            name='age_of_property_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bhk_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cabins_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='co_broker_agency',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='co_broker_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='co_broker_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='commercial_fitout',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Bare Shell'), (1, 'Warm Shell'), (2, 'Plug & Play (Furnished)')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='commission_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='expected_rental_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'North'), (1, 'East'), (2, 'North-East'), (3, 'North-West'), (4, 'South'), (5, 'South-East'), (6, 'South-West'), (7, 'West')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_all_inclusive_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_co_broke_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_corner_plot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='key_arrangement',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'With Owner (Call Prior)'), (1, 'With Security Guard / Caretaker'), (2, 'At Agency Office / Lockbox'), (3, 'Vacant (Self Access / Keypad)'), (4, 'Tenant Occupied (24h Notice)')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='key_contact_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lock_in_period_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mandate_type',
            field=models.SmallIntegerField(choices=[(0, 'Exclusive Mandate'), (1, 'Open Listing')], default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='meeting_rooms_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Vacant'), (1, 'Owner Occupied'), (2, 'Tenanted (Leased)')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Freehold'), (1, 'Leasehold'), (2, 'Co-operative Society'), (3, 'Power of Attorney (GPA)')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No Parking'), (1, 'Covered Parking'), (2, 'Open Parking'), (3, 'Stilt Parking'), (4, 'Mechanical / Hydraulic')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_width_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='society_or_project_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='standard_amenity_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='super_built_up_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tower_block_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='workstations_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='linked_property_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property_category_wanted',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Residential'), (1, 'Commercial')], null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property_sub_type_wanted',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Apartment / Flat'), (1, 'House / Villa'), (2, 'Builder Floor'), (3, 'Penthouse'), (4, 'Studio / 1 RK'), (5, 'Residential Plot'), (6, 'Farmhouse'), (7, 'Office Space'), (8, 'Retail Shop'), (9, 'Showroom'), (10, 'Warehouse / Godown'), (11, 'Industrial Shed / Factory'), (12, 'Commercial Plot / SCO'), (13, 'Agricultural Land'), (14, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='transaction_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Buy / Sell'), (1, 'Rent / Lease')], null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='workflow_status',
            field=models.SmallIntegerField(choices=[(0, 'New Lead'), (1, 'Callback'), (2, 'Interested'), (3, 'Not Connected'), (4, 'Meeting'), (5, 'Negotiation'), (6, 'Won'), (7, 'Lost'), (8, 'Number Issue')], default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_unit',
            field=models.SmallIntegerField(choices=[(0, 'sq.ft.'), (1, 'sq.yd. (Gaj)'), (2, 'Acre'), (3, 'Bigha')], default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Residential'), (1, 'Commercial')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Unfurnished'), (1, 'Semi-Furnished'), (2, 'Fully Furnished')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Under Negotiation'), (2, 'Sold'), (3, 'Rented'), (4, 'Delisted')], default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='possession_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Ready to Move'), (1, 'Under Construction')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sub_type',
            field=models.SmallIntegerField(choices=[(0, 'Apartment / Flat'), (1, 'House / Villa'), (2, 'Builder Floor'), (3, 'Penthouse'), (4, 'Studio / 1 RK'), (5, 'Residential Plot'), (6, 'Farmhouse'), (7, 'Office Space'), (8, 'Retail Shop'), (9, 'Showroom'), (10, 'Warehouse / Godown'), (11, 'Industrial Shed / Factory'), (12, 'Commercial Plot / SCO'), (13, 'Agricultural Land'), (14, 'Other')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(0, 'Buy / Sell'), (1, 'Rent / Lease')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='visibility',
            field=models.SmallIntegerField(choices=[(0, 'Private Listing'), (1, 'Public Marketplace')], default=0),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media_type',
            field=models.SmallIntegerField(choices=[(0, 'Image'), (1, 'Video'), (2, 'Floor Plan'), (3, 'Brochure')], default=0),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='upload_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Uploading'), (2, 'Completed'), (3, 'Failed')], default=0),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at_server', models.DateTimeField(auto_now_add=True)),
                ('updated_at_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at_server', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_agent_id', models.UUIDField(blank=True, null=True)),
                ('project_name', models.CharField(db_index=True, max_length=200)),
                ('developer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('master_rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_land_area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_towers', models.IntegerField(blank=True, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('expected_handover_date', models.DateTimeField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line', models.TextField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('standard_amenity_ids', models.JSONField(blank=True, default=list)),
                ('custom_amenities', models.JSONField(blank=True, default=list)),
                ('master_brochure_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('master_layout_plan_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.tenant')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='crm.project'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'project'], name='prop_project_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'project_name'], name='proj_name_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'city', 'locality'], name='proj_location_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'updated_at_server'], name='proj_sync_idx'),
        ),
    ]
